### PR TITLE
RFC: PHP Error Handling

### PR DESCRIPTION
**Pull request by cjuner**
An opinionated Request for Comments regarding error handling in PHP. It's certainly incomplete in that it does not prescribe a specific behavior in every case.

This addendum is, fow now, to be considered an RFC, i.e., a Request for
Comments. This is not final. Please comment. Please discuss specific issues
occuring during developing or reviewing regarding this topic in the pull
request.
 
We have discussed this together in part (@fixpunkt, @niklasbuechner, @stefanheppenheimer, @hanneswernery and @cjuner). This specific RFC is even more opion-based, because it is more explicit in some areas than discussed in our shared session. This RFC does not represent every attendee's position. We have decided to observe our own experiences and behaviors in situations regarding this topic occuring within the next two weeks, and then revisit this topic.

Note: Unnecessary white-space change above the new section will be fixed later.

### CODE REVIEW

**Comment by fixpunkt** [comment]
Some point @windaishi and I noticed today:

One of the main issues with having dedicated exception classes for every module as part of that module's interface is that this would pollute the exception namespace (e.g. `ViisonCommon\Classes\Exceptions`), which would in turn make it hard to pick the correct exception when you need to throw something from a different module.

However, it turns out this is because our folder structure sorts by source entity type, not by module. Once we move to a module-based directory hierarchy, this problem disappears and we can just have some extra exceptions living with their module without hurting the understandability of the rest of the code base.

**Comment by cjuner** [comment]
@windaishi reported there is an "internal consent" on this issue, which just hasn't been written down yet.

**Comment by fixpunkt** [comment]
Another interesting article I just stumbled upon (from a .NET person, but the concepts nevertheless apply):

https://blogs.msdn.microsoft.com/kcwalina/2007/01/30/how-to-design-exception-hierarchies/

**Comment by windaishi** [comment]
Real life was faster than discussion: https://www.notion.so/pickware/Exceptions-Best-Practice-efd4e1d7c7df425aa4992a36d0dd7833

**Pull request closed without merging**
